# Comment that will be sent if an issue is judged to be closed
comment: "This issue was automatically closed by our bot because it does not meet our issue template requirements. Please **fill in** the questions/sections which are tagged as <!--REQUIRED--> in the **issue template** before submitting a new issue... Please also consider asking any coding questions on Stack Overflow. Thank you."
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: bug report
  - "Describe the Bug"
  - "Steps to Reproduce"
  - "Expected Behavior"
  - "Current Behavior"
- content:
# Example 2: feature request
  - "Motivation / Use Case"
  - "Expected Behavior"
  - "Other Information"
- content:
# Example 3: general
  - "Context"
# The bot will ignore any issues that are opened or reopened by the user names in exception
exception:
  - "ghiscoding"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
